version: '3.7'

networks:
  elastic:

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: FinSum
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - '5432:5432'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    networks:
      - elastic
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    networks:
      - elastic
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601