name: tests

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  tests_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello Step
        run: |
          pwd
          ls -a 
      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: 16.17
      - name: Install Dependecny
        run: |
          cd frontend
          yarn
          yarn test

  tests_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello Step
        run: |
          pwd
          ls -a 
      - name: Setup Node
        uses: actions/setup-node@v2
        with: 
          node-version: 16.17
      - name: Install Dependecny
        run: |
          cd backend
          yarn
      - name: Run Tests
        run: |
          cd backend
          yarn test